version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies"
      
  build:
    commands:
      - echo "Running unit tests"
      - python -m unittest test_app.py

  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
